#!/usr/bin/env node
import { readFileSync, statSync } from "node:fs";
import mysql from "mysql2/promise";
const [command, ...args] = process.argv.slice(2); const option = (name) => { const i = args.indexOf(name); return i < 0 ? undefined : args[i + 1]; };
const secretsFile = option("--secrets-file"); if (!secretsFile || !["apply", "verify"].includes(command)) throw new Error("Usage: mysql-planes.mjs apply|verify --secrets-file FILE"); if ((statSync(secretsFile).mode & 0o077) !== 0) throw new Error("Secrets file must be mode 0600.");
const secrets = JSON.parse(readFileSync(secretsFile, "utf8")); for (const name of ["adminUrl", "scientificIngestPassword", "scientificReadPassword", "operationalAppPassword", "operationalMigratePassword"]) if (typeof secrets[name] !== "string" || !secrets[name]) throw new Error(`Missing ${name}.`);
const account = (user) => `'${user.replaceAll("'", "''")}'@'localhost'`; const users = { ingest: "aiale_scientific_ingest", read: "aiale_scientific_read", app: "aiale_operational_app", migrate: "aiale_operational_migrate" };
const root = await mysql.createConnection(secrets.adminUrl);
async function connectAs(user, password, database) { const url = new URL(secrets.adminUrl); url.username = user; url.password = password; url.pathname = `/${database}`; return mysql.createConnection(url.toString()); }
try {
  if (command === "apply") {
    await root.query("CREATE DATABASE IF NOT EXISTS `aiale_scientific_a3a286b4` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs"); await root.query("CREATE DATABASE IF NOT EXISTS `aiale_operational` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs");
    for (const [key, user] of Object.entries(users)) { const password = secrets[`${key === "app" ? "operationalApp" : key === "migrate" ? "operationalMigrate" : `scientific${key[0].toUpperCase()}${key.slice(1)}`}Password`]; await root.query(`CREATE USER IF NOT EXISTS ${account(user)} IDENTIFIED BY '${password.replaceAll("'", "''")}'`); await root.query(`ALTER USER ${account(user)} IDENTIFIED BY '${password.replaceAll("'", "''")}'`); }
    await root.query(`GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP ON \`aiale_scientific_a3a286b4\`.* TO ${account(users.ingest)}`); await root.query(`GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP ON \`aiale\\_scientific\\_a3a286b4\\_\\_candidate\\_%\`.* TO ${account(users.ingest)}`); await root.query(`GRANT SELECT ON \`aiale_scientific_a3a286b4\`.* TO ${account(users.read)}`); await root.query(`GRANT SELECT ON \`aiale\\_scientific\\_a3a286b4\\_\\_candidate\\_%\`.* TO ${account(users.read)}`); await root.query(`GRANT SELECT, INSERT, UPDATE, DELETE ON \`aiale_operational\`.* TO ${account(users.app)}`); await root.query(`GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP ON \`aiale_operational\`.* TO ${account(users.migrate)}`); await root.query("FLUSH PRIVILEGES"); console.log("PASS planes-created");
  } else {
    let failed = false; const checks = [["scientific-read-select", users.read, secrets.scientificReadPassword, "aiale_scientific_a3a286b4", "SELECT 1"], ["scientific-read-denied-write", users.read, secrets.scientificReadPassword, "aiale_scientific_a3a286b4", "CREATE TABLE grant_probe (id INT)"], ["operational-app-write", users.app, secrets.operationalAppPassword, "aiale_operational", "INSERT INTO job (id) VALUES ('grant-probe')"], ["operational-app-denied-scientific", users.app, secrets.operationalAppPassword, "aiale_scientific_a3a286b4", "SELECT 1 FROM scientific_snapshot_catalog"]];
    for (const [name, user, password, database, sql] of checks) { let passed = false; const shouldDeny = name.includes("denied"); let connection; try { connection = await connectAs(user, password, database); await connection.query(sql); passed = !shouldDeny; } catch { passed = shouldDeny; } finally { await connection?.end(); } console.log(`${passed ? "PASS" : "FAIL"} ${name}`); failed ||= !passed; }
    if (failed) process.exitCode = 1;
  }
} finally { await root.end(); }
