#!/usr/bin/env node
import { readFileSync, statSync } from "node:fs";
import mysql from "mysql2/promise";
const [command, ...args] = process.argv.slice(2); const option = (name) => { const i = args.indexOf(name); return i < 0 ? undefined : args[i + 1]; };
const secretsFile = option("--secrets-file"); if (!secretsFile || !["apply", "verify"].includes(command)) throw new Error("Usage: mysql-planes.mjs apply|verify --secrets-file FILE"); if ((statSync(secretsFile).mode & 0o077) !== 0) throw new Error("Secrets file must be mode 0600.");
const secrets = JSON.parse(readFileSync(secretsFile, "utf8")); for (const name of ["adminUrl", "scientificIngestPassword", "scientificReadPassword", "operationalAppPassword", "operationalMigratePassword"]) if (typeof secrets[name] !== "string" || !secrets[name]) throw new Error(`Missing ${name}.`);
const account = (user) => `'${user.replaceAll("'", "''")}'@'localhost'`; const users = { ingest: "aiale_scientific_ingest", read: "aiale_scientific_read", app: "aiale_operational_app", migrate: "aiale_operational_migrate" }; const scientific = "aiale_scientific_a3a286b4", operational = "aiale_operational";
const root = await mysql.createConnection(secrets.adminUrl);
async function connectAs(user, password, database) { const url = new URL(secrets.adminUrl); url.username = user; url.password = password; url.pathname = `/${database}`; return mysql.createConnection(url.toString()); }
async function runs(name, user, password, database, sql, expected) { let actual; let connection; try { connection = await connectAs(user, password, database); await connection.query(sql); actual = "allow"; } catch { actual = "deny"; } finally { await connection?.end(); } const passed = actual === expected; console.log(`${passed ? "PASS" : "FAIL"} ${name}`); return passed; }
try {
  if (command === "apply") {
    await root.query(`CREATE DATABASE IF NOT EXISTS \`${scientific}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs`); await root.query(`CREATE DATABASE IF NOT EXISTS \`${operational}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs`);
    for (const [key, user] of Object.entries(users)) { const password = secrets[`${key === "app" ? "operationalApp" : key === "migrate" ? "operationalMigrate" : `scientific${key[0].toUpperCase()}${key.slice(1)}`}Password`]; await root.query(`CREATE USER IF NOT EXISTS ${account(user)} IDENTIFIED BY '${password.replaceAll("'", "''")}'`); await root.query(`ALTER USER ${account(user)} IDENTIFIED BY '${password.replaceAll("'", "''")}'`); await root.query(`REVOKE ALL PRIVILEGES, GRANT OPTION FROM ${account(user)}`); }
    await root.query(`GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP ON \`${scientific}\`.* TO ${account(users.ingest)}`); await root.query(`GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP ON \`aiale\\_scientific\\_a3a286b4\\_\\_candidate\\_%\`.* TO ${account(users.ingest)}`); await root.query(`GRANT SELECT ON \`${scientific}\`.* TO ${account(users.read)}`); await root.query(`GRANT SELECT ON \`aiale\\_scientific\\_a3a286b4\\_\\_candidate\\_%\`.* TO ${account(users.read)}`); await root.query(`GRANT SELECT, INSERT, UPDATE, DELETE ON \`${operational}\`.* TO ${account(users.app)}`); await root.query(`GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP ON \`${operational}\`.* TO ${account(users.migrate)}`); await root.query("FLUSH PRIVILEGES"); console.log("PASS planes-created");
  } else {
    const checks = [
      ["scientific-read-select", users.read, secrets.scientificReadPassword, scientific, "SELECT COUNT(*) FROM scientific_table_allowlist", "allow"], ["scientific-read-denied-write", users.read, secrets.scientificReadPassword, scientific, "CREATE TABLE grant_probe (id INT)", "deny"], ["scientific-read-denied-operational", users.read, secrets.scientificReadPassword, operational, "SELECT 1 FROM job", "deny"],
      ["ingest-denied-operational", users.ingest, secrets.scientificIngestPassword, operational, "SELECT 1 FROM job", "deny"], ["migrator-denied-scientific", users.migrate, secrets.operationalMigratePassword, scientific, "SELECT 1 FROM scientific_snapshot_catalog", "deny"], ["operational-app-denied-scientific", users.app, secrets.operationalAppPassword, scientific, "SELECT 1 FROM scientific_snapshot_catalog", "deny"], ["operational-app-write", users.app, secrets.operationalAppPassword, operational, "INSERT INTO job (id, version, kind, status, payload) VALUES ('grant-probe', 1, 'probe', 'done', '{}')", "allow"]
    ]; let failed = false; for (const check of checks) failed ||= !await runs(...check);
    for (const [key, user] of Object.entries(users)) { const [grants] = await root.query(`SHOW GRANTS FOR ${account(user)}`); const hasGlobal = grants.some((row) => Object.values(row).some((value) => /ON \*\.\*/.test(String(value)))); const passed = !hasGlobal; console.log(`${passed ? "PASS" : "FAIL"} ${key}-no-global-grants`); failed ||= !passed; }
    if (failed) process.exitCode = 1;
  }
} finally { await root.end(); }
