'use client';
/* eslint-disable react-hooks/set-state-in-effect -- localStorage hydration initializes client-only editor state. */
import Link from 'next/link';
import { useEffect, useReducer, useRef, useState } from 'react';
import { adjacentWell, allWellIds, createCondition, createPlate } from './document';
import { createPlateState, exportCsv, exportDocument, importDocument, plateReducer } from './state';
import { reviewPlateDocument } from './validation-review';
import type { WellId } from './types';
import { loadStore, saveStore, updateWorkspace } from '../workspaces/local-repository';
const download = (name: string, contents: string, type: string) => { const url = URL.createObjectURL(new Blob([contents], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); };
export default function PlateWorkspace({ designId }: Readonly<{ designId: string }>) {
  const [missing, setMissing] = useState(false); const [ready, setReady] = useState(false); const [storageError, setStorageError] = useState(''); const [conflict, setConflict] = useState(false); const [state, dispatch] = useReducer(plateReducer, undefined, () => createPlateState()); const [selected, setSelected] = useState<string>(); const input = useRef<HTMLInputElement>(null); const hydrated = useRef(false); const pending = useRef(false);
  const reload = () => { const loaded = loadStore(window.localStorage); if (!loaded.ok) { setStorageError(loaded.message); return; } const workspace = loaded.value.workspaces.find(item => item.id === designId); if (!workspace) { setMissing(true); return; } hydrated.current = false; pending.current = false; dispatch({ type: 'replace', document: workspace.document }); setConflict(false); setReady(true); };
  useEffect(() => { reload(); const onStorage = (event: StorageEvent) => { if (event.key !== "viewer2.workspaces.v1") return; if (pending.current) setConflict(true); else reload(); }; window.addEventListener("storage", onStorage); return () => window.removeEventListener("storage", onStorage); // reload is deliberately local to this render.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [designId]);
  useEffect(() => { if (!ready) return; if (!hydrated.current) { hydrated.current = true; return; } pending.current = true; const loaded = loadStore(window.localStorage); if (!loaded.ok) return setStorageError(loaded.message); const workspace = loaded.value.workspaces.find(item => item.id === designId); if (!workspace) return setMissing(true); const saved = saveStore(window.localStorage, updateWorkspace(loaded.value, { ...workspace, document: state.document, snapshots: state.snapshots })); if (!saved.ok) return setStorageError(saved.message); pending.current = false; }, [designId, ready, state.document, state.snapshots]);
  const keepThisTab = () => { pending.current = true; setConflict(false); const loaded = loadStore(window.localStorage); if (!loaded.ok) return setStorageError(loaded.message); const workspace = loaded.value.workspaces.find(item => item.id === designId); if (!workspace) return setMissing(true); const saved = saveStore(window.localStorage, updateWorkspace(loaded.value, { ...workspace, document: state.document, snapshots: state.snapshots })); if (!saved.ok) setStorageError(saved.message); else pending.current = false; };
  if (missing) return <main><p role="alert">This browser-local workspace was not found.</p><Link href="/workspaces">View local workspaces</Link></main>; const plate = state.document.plates[0]; const assigned = plate ? Object.values(plate.wells).filter(Boolean).length : 0; const review = reviewPlateDocument(state.document);
  const move = (event: React.KeyboardEvent<HTMLButtonElement>, well: WellId) => { if (!['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(event.key)) return; event.preventDefault(); const target = adjacentWell(well, event.key as 'ArrowLeft' | 'ArrowRight' | 'ArrowUp' | 'ArrowDown'); if (target) document.getElementById(`well-${target}`)?.focus(); };
  return <main className="min-h-screen bg-[var(--background)] p-4 text-[var(--text)] sm:p-8"><div className="mx-auto max-w-6xl space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="lims-label">Browser-local workspace</p><h1 className="text-2xl font-semibold">96-well Plate Design</h1><p className="text-sm text-[var(--text-soft)]">Local only. This never writes to LIMS.</p></div><div className="flex flex-wrap gap-2"><button className="lims-btn lims-btn-secondary" onClick={() => dispatch({ type: 'undo' })} disabled={!state.past.length}>Undo</button><button className="lims-btn lims-btn-secondary" onClick={() => dispatch({ type: 'redo' })} disabled={!state.future.length}>Redo</button><button className="lims-btn lims-btn-secondary" onClick={() => { const snapshot = { id: crypto.randomUUID(), name: state.document.name, savedAt: new Date().toISOString(), document: state.document }; dispatch({ type: 'snapshot', snapshot }); }}>Snapshot</button></div></header>
   {storageError && <p role="alert" className="rounded border border-red-300 p-3 text-red-700">{storageError}</p>}
   {conflict && <p role="alert" className="rounded border border-amber-300 p-3 text-amber-800">Changed in another tab. <button className="underline" onClick={reload}>Reload</button> or <button className="underline" onClick={keepThisTab}>Keep this tab</button>.</p>}

   {(state.error || state.notice) && <p role={state.error ? 'alert' : 'status'} className={state.error ? 'rounded border border-red-300 p-3 text-red-700' : 'rounded border border-blue-300 p-3 text-blue-700'}>{state.error || state.notice}</p>}
    <section className="lims-surface rounded-lg p-4" aria-labelledby="validation-review-title"><h2 id="validation-review-title" className="font-semibold">Review and validation</h2><p role={review.errors.length ? 'alert' : 'status'} aria-live="polite" className="mt-1 text-sm text-[var(--text-soft)]">{review.summary}</p>{review.errors.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-red-700">{review.errors.map(error => <li key={`${error.path}-${error.message}`}><strong>{error.path}:</strong> {error.message}</li>)}</ul>}</section>
  <section className="lims-surface rounded-lg p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Design name<input className="lims-input mt-1" value={state.document.name} onChange={event => dispatch({ type: 'replace', document: { ...state.document, name: event.target.value } })}/></label><label className="text-sm">Run name<input className="lims-input mt-1" value={state.document.run.name} onChange={event => dispatch({ type: 'replace', document: { ...state.document, run: { ...state.document.run, name: event.target.value } } })}/></label></div></section>
  <section className="grid gap-5 lg:grid-cols-[16rem_1fr]"><aside className="lims-surface rounded-lg p-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Conditions</h2><button aria-label="Add condition" className="lims-btn lims-btn-primary" onClick={() => dispatch({ type: 'add-condition', condition: createCondition(`Condition ${state.document.conditions.length + 1}`) })}>+</button></div><div className="space-y-2">{state.document.conditions.map(condition => <div key={condition.id} className="flex gap-2"><button className="flex-1 rounded border p-2 text-left text-sm" style={{ borderLeftColor: condition.color, borderLeftWidth: 5 }} aria-pressed={selected === condition.id} onClick={() => setSelected(condition.id)}>{condition.name}</button><button aria-label={`Remove ${condition.name}`} onClick={() => dispatch({ type: 'remove-condition', id: condition.id })}>Remove</button></div>)}</div><p className="mt-3 text-xs text-[var(--text-faint)]">Select a condition, then select wells.</p></aside>
  <section className="lims-surface rounded-lg p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-semibold">{plate?.label ?? 'No plate'}</h2><p className="text-sm text-[var(--text-soft)]">{assigned} of 96 wells assigned. Arrow keys move between wells.</p></div><div className="flex gap-2"><button className="lims-btn lims-btn-secondary" onClick={() => plate && dispatch({ type: 'clear-plate', plateId: plate.id })}>Clear</button><button className="lims-btn lims-btn-secondary" disabled={!plate} onClick={() => { if (!plate) return; dispatch({ type: 'duplicate-plate', plateId: plate.id, plate: { ...createPlate(`${plate.label} copy`), wells: structuredClone(plate.wells) } }); }}>+ Duplicate</button><button className="lims-btn lims-btn-primary" onClick={() => dispatch({ type: 'add-plate', plate: createPlate(`Plate ${state.document.plates.length + 1}`) })}>+ Plate</button></div></div>{plate ? <div role="grid" aria-label="96-well plate" className="grid grid-cols-12 gap-1">{allWellIds().map(well => { const assignment = plate.wells[well]; const condition = state.document.conditions.find(item => item.id === assignment?.conditionId); return <button id={`well-${well}`} key={well} role="gridcell" aria-label={`${well}${condition ? `, ${condition.name}` : ', unassigned'}`} className="aspect-square min-w-0 rounded border text-[10px] font-medium focus:outline-none focus:ring-2 focus:ring-blue-600" style={{ background: condition?.color ?? 'transparent' }} onKeyDown={event => move(event, well)} onClick={() => selected ? dispatch({ type: 'assign', plateId: plate.id, wellId: well, conditionId: assignment?.conditionId === selected ? undefined : selected }) : dispatch({ type: 'error', error: 'Select a condition before assigning wells.' })}>{well}</button>; })}</div> : <div className="rounded border border-dashed p-8 text-center"><button className="lims-btn lims-btn-primary" onClick={() => dispatch({ type: 'add-plate', plate: createPlate() })}>Create first plate</button></div>}</section></section>
  <footer className="flex flex-wrap gap-2"><button className="lims-btn lims-btn-secondary" onClick={() => download('plate-design.json', exportDocument(state.document), 'application/json')}>JSON</button><button className="lims-btn lims-btn-secondary" onClick={() => download('plate-assignments.csv', exportCsv(state.document), 'text/csv')}>CSV</button><button className="lims-btn lims-btn-secondary" onClick={() => input.current?.click()}>Import JSON</button><input ref={input} type="file" accept="application/json" className="hidden" onChange={async event => { const file = event.target.files?.[0]; if (!file) return; const result = importDocument(await file.text()); if (result.document) dispatch({ type: 'replace', document: result.document, notice: 'Imported local document.' }); else dispatch({ type: 'error', error: result.error! }); event.target.value = ''; }}/><button className="lims-btn lims-btn-ghost" onClick={() => dispatch({ type: 'discard' })}>Discard draft</button></footer></div></main>; }
