"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Button, InlineNotice, PageHeader, ProvenanceBadge } from "@/components/design-system/Primitives";
import { staticApi } from "@/lib/static-data";
import { activeResultCsv, analysisFigureSvg, downloadHref } from "./analysis-exports";
import { loadCohortSelection, saveCohortSelection, validateCohortSelection } from "./cohort-selection";

const SNAPSHOT_ID = "dev-full-20260726-a86df340";
type Cohort = { experiments: { key: string }[]; registries: { key: string }[]; samples: { key: string }[]; warnings: string[]; capabilities: { hasBarcodes: boolean }; provenance: { snapshotId: string } };
type Result = { rows: Record<string, unknown>[]; summary: { resultCount: number; sampleCount: number }; warnings: string[]; provenance: { snapshotId: string } };
type Kind = "cohort" | "compare" | "growth" | "library-variants" | "copy-number";
export function MutationAnalysis({ kind, title }: Readonly<{ kind: Kind; title: string }>) {
  const [cohort, setCohort] = useState<Cohort>(); const [experimentKey, setExperimentKey] = useState(""); const [registryKey, setRegistryKey] = useState(""); const [sampleKeys, setSampleKeys] = useState<string[]>([]); const [result, setResult] = useState<Result>(); const [error, setError] = useState(""); const hydrated = useRef(false);
  useEffect(() => { staticApi<Cohort>(`/api/v1/mutations/cohort?snapshotId=${SNAPSHOT_ID}${experimentKey ? `&experimentKey=${encodeURIComponent(experimentKey)}` : ""}${registryKey ? `&registryKey=${encodeURIComponent(registryKey)}` : ""}`).then(data => {
    setCohort(data); if (!hydrated.current) { hydrated.current = true; const stored = loadCohortSelection(window.localStorage, data.provenance.snapshotId); if (!stored.ok) setError(stored.message); const selection = validateCohortSelection(stored.ok ? stored.value : undefined, data); if (selection) { setExperimentKey(selection.experimentKey); setRegistryKey(selection.registryKey ?? ""); setSampleKeys(selection.sampleKeys); } }
    else setSampleKeys(current => current.filter(key => data.samples.some(sample => sample.key === key)));
  }).catch((cause: Error) => setError(cause.message)); }, [experimentKey, registryKey]);
  useEffect(() => { if (!experimentKey || !cohort) return; saveCohortSelection(window.localStorage, { schemaVersion: 1, snapshotId: cohort.provenance.snapshotId, experimentKey, ...(registryKey ? { registryKey } : {}), sampleKeys }); }, [cohort, experimentKey, registryKey, sampleKeys]);
  const endpoint = kind === "compare" ? "compare" : kind; const available = kind !== "library-variants" || cohort?.capabilities.hasBarcodes;
  async function run() { if (!experimentKey) return setError("Select an experiment before running an analysis."); if (!sampleKeys.length) return setError("Select at least one sample."); setError(""); try { setResult(await staticApi<Result>(`/api/v1/mutations/${endpoint}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ snapshotId: SNAPSHOT_ID, experimentKey, registryKey: registryKey || undefined, sampleKeys }) })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Analysis is unavailable."); } }
  const csv = useMemo(() => result ? activeResultCsv(result.rows) : "", [result]); const svg = useMemo(() => result ? analysisFigureSvg(title, result.summary) : "", [result, title]);
  if (kind === "cohort") return <section><PageHeader eyebrow="RESEARCH" title={title}>{cohort && <ProvenanceBadge label={cohort.provenance.snapshotId} />}</PageHeader>{error && <InlineNotice tone="warning">{error}</InlineNotice>}<Selectors cohort={cohort} experimentKey={experimentKey} registryKey={registryKey} setExperimentKey={setExperimentKey} setRegistryKey={setRegistryKey} sampleKeys={sampleKeys} setSampleKeys={setSampleKeys} /><p>{sampleKeys.length} samples selected. Choose a comparison from the research navigation to analyze this cohort.</p></section>;
  return <section><PageHeader eyebrow="RESEARCH" title={title}>{cohort && <ProvenanceBadge label={cohort.provenance.snapshotId} />}</PageHeader>{!available && <InlineNotice tone="warning">Library variants is unavailable because this snapshot has no barcode records. Return to the cohort builder.</InlineNotice>}{error && <InlineNotice tone="warning">{error}</InlineNotice>}<Selectors cohort={cohort} experimentKey={experimentKey} registryKey={registryKey} setExperimentKey={setExperimentKey} setRegistryKey={setRegistryKey} sampleKeys={sampleKeys} setSampleKeys={setSampleKeys} /><Button disabled={!available} onClick={run}>Run analysis</Button>{result && <><h2>Accessible summary</h2><p>{result.summary.resultCount} results across {result.summary.sampleCount} selected samples.</p><figure><svg aria-labelledby="analysis-figure-title analysis-figure-description" role="img" viewBox="0 0 540 210"><title id="analysis-figure-title">{title}</title><desc id="analysis-figure-description">A bar chart of results and selected samples.</desc>{[{ label: "Results", value: result.summary.resultCount }, { label: "Selected samples", value: result.summary.sampleCount }].map((item, index) => <g key={item.label}><text x="20" y={90 + index * 55}>{item.label}: {item.value}</text><rect x="190" y={70 + index * 55} width={Math.round(item.value / Math.max(1, result.summary.resultCount, result.summary.sampleCount) * 300)} height="28" /></g>)}</svg><figcaption>Analysis summary figure. The active result table provides the underlying values.</figcaption></figure><h3>Legend</h3><ul><li>Bars show result and selected-sample counts.</li><li>Values appear in the active result table and are not inferred from the figure.</li></ul>{result.warnings.map(warning => <InlineNotice key={warning} tone="warning">{warning}</InlineNotice>)}<table><caption>Active analysis result</caption><thead><tr>{Object.keys(result.rows[0] ?? {}).map(key => <th key={key}>{key}</th>)}</tr></thead><tbody>{result.rows.map((row, index) => <tr key={index}>{Object.entries(row).map(([key, value]) => <td key={key}>{typeof value === "object" ? JSON.stringify(value) : String(value ?? "")}</td>)}</tr>)}</tbody></table>{csv && <p><a download={`${endpoint}.csv`} href={downloadHref("text/csv", csv)}>Download active result CSV</a>{" · "}<a download={`${endpoint}-summary.svg`} href={downloadHref("image/svg+xml", svg)}>Download summary figure SVG</a></p>}</>}</section>;
}
function Selectors({ cohort, experimentKey, registryKey, setExperimentKey, setRegistryKey, sampleKeys, setSampleKeys }: Readonly<{ cohort?: Cohort; experimentKey: string; registryKey: string; setExperimentKey: (value: string) => void; setRegistryKey: (value: string) => void; sampleKeys: string[]; setSampleKeys: (value: string[]) => void }>) { return <fieldset disabled={!cohort}><legend>Cohort selection</legend><label>Experiment <select value={experimentKey} onChange={event => setExperimentKey(event.target.value)}><option value="">Select an experiment</option>{cohort?.experiments.map(({ key }) => <option key={key}>{key}</option>)}</select></label><label>Registry <select value={registryKey} onChange={event => setRegistryKey(event.target.value)}><option value="">All registries</option>{cohort?.registries.map(({ key }) => <option key={key}>{key}</option>)}</select></label><div aria-label="Samples">{cohort?.samples.map(({ key }) => <label key={key}><input type="checkbox" checked={sampleKeys.includes(key)} onChange={event => setSampleKeys(event.target.checked ? [...sampleKeys, key] : sampleKeys.filter(sample => sample !== key))} />{key}</label>)}</div>{cohort?.warnings.map(warning => <InlineNotice key={warning} tone="warning">{warning}</InlineNotice>)}</fieldset>; }
