"use client";
import { useEffect, useMemo, useState } from "react";
import { Button, InlineNotice, PageHeader, ProvenanceBadge } from "@/components/design-system/Primitives";
import { staticApi } from "@/lib/static-data";

const SNAPSHOT_ID = "dev-full-20260726-a86df340";
type Cohort = { experiments: { key: string }[]; registries: { key: string }[]; samples: { key: string }[]; warnings: string[]; capabilities: { hasBarcodes: boolean }; provenance: { snapshotId: string } };
type Result = { rows: Record<string, unknown>[]; summary: { resultCount: number; sampleCount: number }; warnings: string[]; provenance: { snapshotId: string } };
export function MutationAnalysis({ kind, title }: Readonly<{ kind: "cohort" | "compare" | "growth" | "library-variants" | "copy-number"; title: string }>) {
 const [cohort, setCohort] = useState<Cohort>(); const [experimentKey, setExperimentKey] = useState(""); const [registryKey, setRegistryKey] = useState(""); const [sampleKeys, setSampleKeys] = useState<string[]>([]); const [result, setResult] = useState<Result>(); const [error, setError] = useState("");
  useEffect(() => { staticApi<Cohort>(`/api/v1/mutations/cohort?snapshotId=${SNAPSHOT_ID}${experimentKey ? `&experimentKey=${encodeURIComponent(experimentKey)}` : ""}${registryKey ? `&registryKey=${encodeURIComponent(registryKey)}` : ""}`).then((data) => { setCohort(data); setSampleKeys((current) => current.filter((key) => data.samples.some((sample: { key: string }) => sample.key === key))); }).catch((cause: Error) => setError(cause.message)); }, [experimentKey, registryKey]);
 const endpoint = kind === "compare" ? "compare" : kind; const available = kind !== "library-variants" || cohort?.capabilities.hasBarcodes;
  async function run() { if (!experimentKey) return setError("Select an experiment before running an analysis."); if (!sampleKeys.length) return setError("Select at least one sample."); setError(""); try { setResult(await staticApi<Result>(`/api/v1/mutations/${endpoint}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ snapshotId: SNAPSHOT_ID, experimentKey: experimentKey || "all", registryKey: registryKey || undefined, sampleKeys }) })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Analysis is unavailable."); } }
 const csv = useMemo(() => result ? [Object.keys(result.rows[0] ?? {}).join(","), ...result.rows.map((row) => Object.values(row).map((value) => JSON.stringify(value ?? "")).join(","))].join("\r\n") : "", [result]);
 if (kind === "cohort") return <section><PageHeader eyebrow="RESEARCH" title={title}>{cohort && <ProvenanceBadge label={cohort.provenance.snapshotId} />}</PageHeader>{error && <InlineNotice tone="warning">{error}</InlineNotice>}<Selectors cohort={cohort} experimentKey={experimentKey} registryKey={registryKey} setExperimentKey={setExperimentKey} setRegistryKey={setRegistryKey} sampleKeys={sampleKeys} setSampleKeys={setSampleKeys} /><p>{sampleKeys.length} samples selected. Choose a comparison from the research navigation to analyze this cohort.</p></section>;
 return <section><PageHeader eyebrow="RESEARCH" title={title}>{cohort && <ProvenanceBadge label={cohort.provenance.snapshotId} />}</PageHeader>{!available && <InlineNotice tone="warning">Library variants is unavailable because this snapshot has no barcode records. Return to the cohort builder.</InlineNotice>}{error && <InlineNotice tone="warning">{error}</InlineNotice>}<Selectors cohort={cohort} experimentKey={experimentKey} registryKey={registryKey} setExperimentKey={setExperimentKey} setRegistryKey={setRegistryKey} sampleKeys={sampleKeys} setSampleKeys={setSampleKeys} /><Button disabled={!available} onClick={run}>Run analysis</Button>{result && <><h2>Accessible summary</h2><p>{result.summary.resultCount} results across {result.summary.sampleCount} selected samples.</p>{result.warnings.map((warning) => <InlineNotice key={warning} tone="warning">{warning}</InlineNotice>)}<table><caption>Active analysis result</caption><thead><tr>{Object.keys(result.rows[0] ?? {}).map((key) => <th key={key}>{key}</th>)}</tr></thead><tbody>{result.rows.map((row, index) => <tr key={index}>{Object.entries(row).map(([key, value]) => <td key={key}>{typeof value === "object" ? JSON.stringify(value) : String(value ?? "")}</td>)}</tr>)}</tbody></table>{csv && <a download={`${endpoint}.csv`} href={`data:text/csv;charset=utf-8,${encodeURIComponent(csv)}`}>Download active result CSV</a>}</>}</section>;
}
function Selectors({ cohort, experimentKey, registryKey, setExperimentKey, setRegistryKey, sampleKeys, setSampleKeys }: Readonly<{ cohort?: Cohort; experimentKey: string; registryKey: string; setExperimentKey: (value: string) => void; setRegistryKey: (value: string) => void; sampleKeys: string[]; setSampleKeys: (value: string[]) => void }>) { return <fieldset disabled={!cohort}><legend>Cohort selection</legend><label>Experiment <select value={experimentKey} onChange={(event) => setExperimentKey(event.target.value)}><option value="">All experiments</option>{cohort?.experiments.map(({ key }) => <option key={key}>{key}</option>)}</select></label><label>Registry <select value={registryKey} onChange={(event) => setRegistryKey(event.target.value)}><option value="">All registries</option>{cohort?.registries.map(({ key }) => <option key={key}>{key}</option>)}</select></label><div aria-label="Samples">{cohort?.samples.map(({ key }) => <label key={key}><input type="checkbox" checked={sampleKeys.includes(key)} onChange={(event) => setSampleKeys(event.target.checked ? [...sampleKeys, key] : sampleKeys.filter((sample) => sample !== key))} />{key}</label>)}</div>{cohort?.warnings.map((warning) => <InlineNotice key={warning} tone="warning">{warning}</InlineNotice>)}</fieldset>; }
